x<-read.csv("oneanaova.csv")
class(x)
class(x$X..Batch.)
class(x$Y.happiness.level.)
table(x$X..Batch.)
x$X..Batch.<-as.factor(x$X..Batch.)
class(x$X..Batch.)
aov(Y.happiness.level.~X..Batch., x)
summary(aov(Y.happiness.level.~X..Batch., x))
boxplot(x$Y.happiness.level.~x$X..Batch.)
TukeyHSD(aov(Y.happiness.level.~X..Batch., x))
bartlett.test(Y.happiness.level.~X..Batch., x)
y<-read.csv("twoway.csv")
str(y)

y$Gender<-as.factor(y$Gender)
y$Batch<-as.factor(y$Batch)
summary(aov(happiness.level~Batch * Gender , y))
summary(aov(happiness.level~Batch + Gender , y))
boxplot(y$happiness.level~y$Batch + y$Gender)
interaction.plot(y$happiness.level,y$Batch, y$Gender)

summary(aov(happiness.level~Batch + Gender + Batch : Gender, y))
graphics.off()
